### ISSUE TITLE
Not seeing the duplicated item appear

### ISSUE THREAD

**Issue by GoodDiv** [gegedenice/ItemCopy#1]

**Comment by gegedenice** [comment]
Hi, sorry i didn't get an email notification for your issue so i didn't see it...
Is this still an issue? If yes, since the module is written in javascript, you can check on what happens in the browser console

**Comment by GoodDiv** [comment]
Thanks so much for getting back to me! The issue was resolved a while ago,
I think it had something to do with enabling or editing something with
javascript. I find this a very useful tool, thank you for creating it!




*Jennifer Goodwin*
Library Web Developer
:::::::::::::::::::::::::::::::::::::::::
518.388.6063
goodwinj@union.edu
:::::::::::::::::::::::::::::::::::::::::
SCHAFFER LIBRARY
UNION COLLEGE

**Comment by gegedenice** [comment]
You're welcome ! I'm glad it wasn't anymore than enabling Javascript, and if this module is useful to you...

**Comment by COPES3D** [comment]
Hi, I'm having the same problem... Could you please help me?
Thanks in advance!
